const configurableTypes = {
    USER_ACTIONS : {
        ACCESS_SUBJECT_REGISTRATION : 'ACCESS_SUBJECT_REGISTRATION',
        DELETED_SUBJECT_PROFILE     : 'DELETED_SUBJECT_PROFILE',
        SUBJECT_ATTACHED_TOKEN      : 'SUBJECT_ATTACHED_TOKEN',
        SUBJECT_ENABLED_TOKEN       : 'SUBJECT_ENABLED_TOKEN',
        SUBJECT_DISABLED_TOKEN      : 'SUBJECT_DISABLED_TOKEN',
        SUBJECT_DETACHED_TOKEN      : 'SUBJECT_DETACHED_TOKEN'
    },
    READER_STATE : {
        ACTIVE_READER   : 'ACTIVE_READER',
        INACTIVE_READER : 'INACTIVE_READER'
    },
    ACCESS_ATTEMPTS : {
        UNAUTH_SUBJECT_ACCESS     : 'UNAUTH_SUBJECT_ACCESS',
        UNAUTH_SUBJECT_PHN_ACCESS : 'UNAUTH_SUBJECT_PHN_ACCESS',
        UNAUTH_ACCESS             : 'UNAUTH_ACCESS'
    }
};

const alwaysEnabledTypes = {
    NEW_READER    : 'NEW_READER',
    UNKNOWN_TOKEN : 'UNKNOWN_TOKEN'
};

export {
    configurableTypes,
    alwaysEnabledTypes
};
