const TEMPLATE_TYPES = {
    ACTIVATE_USER            : 'ACTIVATE_USER',
    RESET_PASSWORD_WITH_URL  : 'RESET_PASSWORD_WITH_URL',
    RESET_PASSWORD_WITH_CODE : 'RESET_PASSWORD_WITH_CODE',
    INVITE_ACCESS_SUBJECT    : 'INVITE_ACCESS_SUBJECT',
    REPORTED_GENERIC_ISSUE   : 'REPORTED_GENERIC_ISSUE'
};

export default {
    TEMPLATE_TYPES
};
