const TYPES = {
    RESET_USER_PASSWORD       : 'RESET_USER_PASSWORD',
    RESET_ADMIN_PASSWORD      : 'RESET_ADMIN_PASSWORD',
    LOGIN_ATTEMPTS            : 'LOGIN_ATTEMPTS',
    USER_REQUEST_REGISTRATION : 'USER_REQUEST_REGISTRATION'
};

export {
    TYPES
};
