/* eslint-disable key-spacing */
const mapping = {
    TOO_SHORT               : 'String is too short',
    TOO_LONG                : 'String is too long',
    LIST_TOO_LONG           : 'List is too long',
    REQUIRED                : 'Value is required',
    NOT_INTEGER             : 'Value should be integer',
    NOT_POSITIVE_INTEGER    : 'Value should be positive integer',
    NOT_BOOLEAN             : 'Value should be boolean',
    TOO_LOW                 : 'Value is too low',
    TOO_HIGH                : 'Value is too high',
    CANNOT_BE_EMPTY         : 'Value is required',
    NOT_DECIMAL             : 'Value is not decimal',
    NOT_ALLOWED_VALUE       : 'Not allowed value',
    WRONG_END_OF_DATE_RANGE : 'Wrong end of date range',
    WRONG_DATE              : 'Wrong date',
    WRONG_PASSWORD_FORMAT   : 'Wrong password format',
    FIELDS_NOT_EQUAL        : 'Fields not equal',
    CANNOT_CHANGE_PASSWORD_TO_THE_SAME : 'You\'ve entered the same passwords',
    WRONG_PHONE_FORMAT      : 'Wrong phone format',
    WRONG_EMAIL             : 'Wrong email format',
    TOO_FEW_ITEMS           : 'Too few items',
    TOO_MANY_ITEMS          : 'Too many items',
    WRONG_TIME_FORMAT       : 'Wrong time format',
    WRONG_DATE_FORMAT       : 'Wrong date format',
    LIST_HAS_DUPLICATES     : 'List has duplicates',
    NOT_UNIQUE_ITEMS        : 'Not unique items',
    FORMAT_ERROR            : 'Format error',
    WRONG_ID                : 'Wrong id',
    WRONG_URL_FORMAT        : 'Wrong url format',
    WRONG_FORMAT            : 'Wrong format',
    WRONG_LOGIN_FORMAT      : 'Only a-z, A-Z letters and 0-9 digits',
    WRONG_TOKEN_READER_CODE_FORMAT : 'Only a-z, A-Z letters, 0-9 digits and :, -, _',
    WRONG_ACCESS_SUBJECT_TOKEN_CODE_FORMAT : 'Only A-Z letters and 0-9 digits',
    WRONG_WORKSPACE_NAME_FORMAT : 'Only a-z letters and 0-9 digits',
    REQUIRED_EMAIL_ON_MOBILE : 'The field is required for mobile application',
    TOO_SHORT_PASSWORD       : 'Too short password',
    PASSWORD_SHOULD_CONTAIN_AT_LEAST_ONE_DIGIT           : 'Password should contain at least one digit',
    PASSWORD_SHOULD_CONTAIN_AT_LEAST_ONE_LOWER_CHARACTER : 'Password should contain at least one lowercase latin character',
    PASSWORD_SHOULD_CONTAIN_AT_LEAST_ONE_UPPER_CHARACTER : 'Password should contain at least one uppercase latin character',
    BAD_ID                       : 'Bad id',
    WRONG_DATES_VALUES_IN_PERIOD : 'Wrong dates values in period',
    WRONG_RTSP_URL               : 'Wrong RTSP url'
};

export default mapping;
